version: 2
jobs:
  build:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - run:
          name: install
          command: npm install
      - run:
          name: build
          command: npm run build
      - run:
          name: test
          command: npm test
      - run:
          name: lint
          command: npm run lint
